name: "Terraform security scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.2.1
        with:
          tfsec_version: "v0.39.22"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
